/**
 * Mock Model Router
 *
 * Mocks the LLM/AI service calls for testing without network requests.
 */

import { vi } from "vitest";

// Default mock response for question generation
export const mockQuestionResponse = {
  title: "[Easy] Mock Generated Question",
  description: "This question was generated by the mock LLM.",
  inputDescription: "An array of integers",
  outputDescription: "The processed result",
  constraints: ["1 <= n <= 100"],
  sampleInput: "[1, 2, 3]",
  sampleOutput: "6",
  starterCode: "def solution(arr):\n    pass",
  testCases: [
    { input: "[1, 2, 3]", expectedOutput: "6", isHidden: false },
    { input: "[1]", expectedOutput: "1", isHidden: false },
  ],
};

// Track call counts
let callCount = 0;
let lastCallArgs: unknown[] = [];

/**
 * Get the mock implementation for callGeminiWithFallback
 */
export function getMockCallGeminiWithFallback() {
  return vi.fn().mockImplementation(async (...args: unknown[]) => {
    callCount++;
    lastCallArgs = args;

    // Return a JSON string that can be parsed
    return JSON.stringify(mockQuestionResponse);
  });
}

/**
 * Get the mock for evaluating code
 */
export function getMockEvaluateCode() {
  return vi.fn().mockImplementation(async () => {
    return {
      isCorrect: true,
      feedback: "Great job! Your solution is correct.",
      executionTime: "O(n)",
      suggestions: [],
    };
  });
}

/**
 * Get the mock for hints
 */
export function getMockGetHint() {
  return vi.fn().mockImplementation(async () => {
    return {
      hint: "Try thinking about the problem step by step.",
      difficulty: "easy",
    };
  });
}

/**
 * Reset mock state
 */
export function resetMockState() {
  callCount = 0;
  lastCallArgs = [];
}

/**
 * Get mock statistics
 */
export function getMockStats() {
  return {
    callCount,
    lastCallArgs,
  };
}

/**
 * Setup model router mocks
 * Call this in your test setup to mock the entire module
 */
export function setupModelRouterMocks() {
  vi.mock("@/lib/ai/modelRouter", () => ({
    callGeminiWithFallback: getMockCallGeminiWithFallback(),
    evaluateCode: getMockEvaluateCode(),
    getHint: getMockGetHint(),
  }));
}
